type dataSchema = {
  id: number,
  title: string,
  image: string,
  category: string,
  subcategory: string,
  episode: string,
  year: number,
  vj: string,
  created_at: string, // this is date?
  modified_at: string, // this is date?
  available_copies: number,
  sold_copies: number,
  price_per_copy: number,
};

export const data: dataSchema[] = [
  {
    id: 1,
    title: 'alita battle angel',
    image: '/images/samples/alita.jpg',
    category: 'action',
    subcategory: 'full movie',
    episode: '1',
    year: 2022,
    vj: 'emmy',
    created_at: '10/14/2022 5:04 PM',
    modified_at: '10/14/2022 5:05 PM',
    available_copies: 6,
    sold_copies: 1,
    price_per_copy: 1500,
  },
  {
    id: 2,
    title: 'queen of the south',
    image: '/images/samples/queen-of-the-south.jpg',
    category: 'action detective',
    subcategory: 'serie',
    episode: '1-4',
    year: 2022,
    vj: 'junior',
    created_at: '10/15/2022 5:04 PM',
    modified_at: '10/14/2022 5:07 AM',
    available_copies: 120,
    sold_copies: 10,
    price_per_copy: 1500,
  },
  {
    id: 3,
    title: 'queen of the south',
    image: '/images/samples/queen-of-the-south.jpg',
    category: 'action detective',
    subcategory: 'serie',
    episode: '5-8',
    year: 2022,
    vj: 'junior',
    created_at: '10/15/2022 5:04 PM',
    modified_at: '10/14/2022 5:07 AM',
    available_copies: 120,
    sold_copies: 5,
    price_per_copy: 1500,
  },
  {
    id: 4,
    title: 'queen of the south',
    image: '/images/samples/queen-of-the-south.jpg',
    category: 'action detective',
    subcategory: 'serie',
    episode: '9-12',
    year: 2022,
    vj: 'junior',
    created_at: '10/15/2022 5:04 PM',
    modified_at: '10/14/2022 5:07 AM',
    available_copies: 120,
    sold_copies: 1,
    price_per_copy: 1500,
  },
  {
    id: 5,
    title: 'queen of the south',
    image: '/images/samples/queen-of-the-south.jpg',
    category: 'action detective',
    subcategory: 'serie',
    episode: '13-16',
    year: 2022,
    vj: 'junior',
    created_at: '10/15/2022 5:04 PM',
    modified_at: '10/14/2022 5:07 AM',
    available_copies: 120,
    sold_copies: 25,
    price_per_copy: 1500,
  },
];
